### ISSUE TITLE
HTML showing up in search results

### ISSUE THREAD

**Issue by zenmatt** [eojthebrave/hackpad-alfred#1]
HTML is showing up in the text of search results.

![screen shot 2013-10-23 at 6 24 17 pm](https://f.cloud.github.com/assets/56040/1395368/47fa9464-3c3a-11e3-9b4d-0e3dd84185bb.png)

**Comment by eojthebrave** [comment]
This should be fixed now if you update to the latest version. I had noticed this a couple of times but kept forgetting to fix it. Thanks for the reminder.
