### ISSUE TITLE
HTML encoded characters are displayed in Alfred

### ISSUE THREAD

**Issue by q0rban** [eojthebrave/hackpad-alfred#2]
If you search for a pad that has an ampersand, the result will have that ampersand HTML encoded:

![2014-05-29 12-11-19](https://cloud.githubusercontent.com/assets/66118/3119974/dfed4f8e-e74b-11e3-878a-e5ab1c7e5367.jpg)

**Comment by eojthebrave** [comment]
This should be working now. Thanks @q0rban.
