### ISSUE TITLE
Does it (still) work?

### ISSUE THREAD

**Issue by jipiboily** [eojthebrave/hackpad-alfred#4]
I just tried it, and would love to get it working! I've setup the URL ("https://something...."), the ID (Client ID I'm assuming) and the key (secret, I'm assuming)...but it doesn't work :(

Here is a video of what it does -> http://sharing.rainforestqa.com/1X303S153T0U

Let me know how I can help debugging this, thanks! :)

**Comment by psteinweber** [comment]
Hey! I've also just set it up and it works for me. First it didn't (did the same thing like it does for you), because I entered the URL incorrectly. I only entered the first part ("something"). When entering "https://something.hackpad.com" (no trailing slash) it works fine. Maybe that helps

**Comment by jipiboily** [comment]
@psteinweber thanks! I moved from Hackpad recently though, I'm not going to try it but I'm assuming you could totally be right and close this :)
